# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users should note that Gradle settings configured in the IDE
# will override any settings specified in this file.
# For more details on how to configure the build environment see
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
# AndroidX package structure to make it clearer which libraries are bundled with the
# Android operating system.
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

kotlin.compiler.execution.strategy=in-process
org.gradle.workers.max=1
